# Generated by Django 5.0.3 on 2024-03-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-knowledge'], 'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
    ]
