# Generated by Django 5.0.3 on 2024-03-12 18:04

import apps.aboutme.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('cv', models.FileField(blank=True, null=True, upload_to=apps.aboutme.models.custom_upload_to_cv)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.aboutme.models.custom_upload_to_image, verbose_name='image')),
                ('videoUrl', models.URLField(blank=True, null=True)),
                ('state', models.BooleanField(default=True, verbose_name='state')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Me',
                'verbose_name_plural': 'About Me',
            },
        ),
    ]
