# Generated by Django 5.0.3 on 2024-03-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
