# Generated by Django 5.0.3 on 2024-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='videoUrl',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
