# Generated by Django 5.0.3 on 2024-03-08 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('phone', models.IntegerField(verbose_name='phone')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(verbose_name='website')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Infos',
            },
        ),
    ]
