# Generated by Django 5.0.3 on 2024-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_user_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, unique=True, verbose_name='category product')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='categoryproject',
            field=models.ManyToManyField(blank=True, to='portfolio.categoryproject', verbose_name='categoty project'),
        ),
    ]
